name: MDReader
options:
  bundleIdPrefix: com.hassanalsheikh
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"

targets:
  MDReader:
    type: application
    platform: macOS
    sources:
      - MDReader
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hassanalsheikh.MDReader
        PRODUCT_NAME: MDReader
        MARKETING_VERSION: "3.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        INFOPLIST_KEY_CFBundleDisplayName: MDReader
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
    dependencies:
      - package: MarkdownUI
    info:
      path: MDReader/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: Markdown Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - net.daringfireball.markdown
              - public.markdown
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: net.daringfireball.markdown
            UTTypeDescription: Markdown Document
            UTTypeConformsTo:
              - public.plain-text
            UTTypeTagSpecification:
              public.filename-extension:
                - md
                - markdown
                - mdown
                - mkd
                - mkdn
